edition = "2021"
max_width = 120
tab_spaces = 2
use_small_heuristics = "Default"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true

