# `sheldon` configuration file
#
# cf.) https://github.com/rossmacarthur/sheldon#readme
# -----

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

# defer execution of a zsh command
# -----
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
branch = "master"


# commands suggestions based on history
# -----
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"
apply = ["defer"]

# commands completion
# -----
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
tag = "0.35.0"
apply = ["defer"]

# [plugins.zsh-abbr]
# github = "olets/zsh-abbr"
# tag = "v6.2.1"
# apply = ["defer"]

# theme: pure
# cf.) https://github.com/sindresorhus/pure
# -----
[plugins.pure]
github = "sindresorhus/pure"
tag = "v1.23.0"
use = ["async.zsh", "pure.zsh"]
apply = ["source"]              # could not be deferred

# commands highlight
# -----
[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
tag = "v1.66"
apply = ["defer"]
